spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contractdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: test
  jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  flyway:
    locations: classpath:db/migration
flyway:
  validate-on-migration: true
  out-of-order: true